1. Import the numpy package under the name np (★☆☆)
hint: import … as

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [2]:
#1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [2]:
#2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
np.random.randint(0,9,(3,3))

array([[4, 2, 8],
       [7, 5, 6],
       [0, 7, 7]])

In [12]:
#6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
b = np.array([1,2,0,0,4,0])
np.nonzero(b)

(array([0, 1, 4], dtype=int64),)

In [14]:
#7. Create a 3x3 identity matrix (★☆☆)
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#8. Create a 3x3x3 array with random values (★☆☆)
d = np.random.random((3,3,3))
d

array([[[0.38655302, 0.79648014, 0.49440043],
        [0.46965262, 0.04990551, 0.09081639],
        [0.72912643, 0.36763741, 0.65307348]],

       [[0.89002529, 0.14157976, 0.15568924],
        [0.59370246, 0.99450623, 0.24932727],
        [0.80621585, 0.00178251, 0.47212706]],

       [[0.2763153 , 0.83688332, 0.44270745],
        [0.68594796, 0.60167744, 0.76387187],
        [0.35778502, 0.03693274, 0.23223962]]])

In [21]:
#9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
e = np.random.random((10,10))
e
print(np.max(e))
print(np.min(e))

0.9980281900113879
0.009892849149389482


In [26]:
#10. Create a random vector of size 30 and find the mean value (★☆☆)
f = np.random.random((30))
print(np.mean(f))

0.5462482618914449


In [33]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
print(1+np.arange(4))
g = np.diag(1+np.arange(4),k=-1)
print(g)

[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [41]:
#12. Normalize a 5x5 random matrix (★☆☆)
h = np.random.random((5,5))
print(h)
hmax, hmin = h.max(), h.min()
print(h.max())
print(hmin)
h = (h-hmin)/(hmax-hmin)
print(h)

[[0.57636013 0.80396404 0.653464   0.49066517 0.89510617]
 [0.79787064 0.24964555 0.1741     0.67921355 0.86678307]
 [0.96904973 0.66765208 0.51336959 0.36617072 0.05885179]
 [0.41802287 0.65190946 0.83094796 0.53254695 0.40169191]
 [0.44776609 0.5137876  0.43016511 0.23693139 0.65869403]]
0.9690497294789154
0.0588517930362733
[[0.5685668  0.8186266  0.65327791 0.474417   0.91876102]
 [0.81193202 0.20961787 0.12661884 0.68156797 0.8876435 ]
 [1.         0.66886581 0.49936149 0.33763966 0.        ]
 [0.39460766 0.65157    0.84827281 0.52043093 0.37666546]
 [0.42728541 0.49982074 0.40794788 0.19564931 0.65902395]]


In [42]:
#13. How to find common values between two arrays? (★☆☆)
np.intersect1d(b,c)

array([0., 1.])

In [43]:
#14. Create a random vector of size 10 and sort it (★★☆)
j = np.random.random(10)
j.sort()
print(j)

[0.01667529 0.01868426 0.03493698 0.23994028 0.32616531 0.46893248
 0.5918871  0.63273195 0.94349673 0.96468945]


In [44]:
#15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
k = np.random.random(15)
print("Original array:")
print(k)
k[k.argmax()] = -1
print("Maximum value replaced by -1:")
print(k)

Original array:
[0.24229843 0.14591158 0.27993622 0.67651554 0.05229795 0.62736564
 0.75247362 0.33714937 0.70227446 0.90496327 0.64486959 0.75986223
 0.61875777 0.23195032 0.66641859]
Maximum value replaced by -1:
[ 0.24229843  0.14591158  0.27993622  0.67651554  0.05229795  0.62736564
  0.75247362  0.33714937  0.70227446 -1.          0.64486959  0.75986223
  0.61875777  0.23195032  0.66641859]


In [45]:
#16. Subtract the mean of each row of a matrix (★★☆)

m = np.random.rand(5, 10)

n = m - m.mean(axis=1, keepdims=True)

print(n)

[[ 0.20319066  0.29104431  0.05363599 -0.29532379  0.04482364  0.04556299
  -0.08188535  0.14828028 -0.4711238   0.06179507]
 [-0.10762801  0.43990242  0.18134275  0.32394475  0.20659878 -0.49410245
  -0.25224621 -0.0688422  -0.00635579 -0.22261404]
 [-0.04661981  0.39205345  0.19219817 -0.257593    0.2514625  -0.49904848
  -0.13068062  0.22419178  0.01248014 -0.13844415]
 [-0.36409881 -0.46930514 -0.00449433  0.00417777  0.04657075 -0.00537402
   0.33661635 -0.27639034  0.45169215  0.28060562]
 [-0.04148196 -0.47489229  0.01801477  0.33853347  0.05538775  0.26107179
   0.24621247 -0.4545283   0.14850043 -0.09681813]]


In [51]:
#17. How to get the 5 largest values of an array (★★★)
p = np.arange(10000) 
np.random.shuffle(p)
print(p)
sorted_index_array = np.argsort(p)
print(sorted_index_array)
sorted_array = p[sorted_index_array]
print(sorted_array)
rslt = sorted_array[-5 : ]
print(rslt)

[ 542 7054 5620 ... 2820  749 5011]
[5810 1414 1441 ... 2089 7431 6322]
[   0    1    2 ... 9997 9998 9999]
[9995 9996 9997 9998 9999]


In [4]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares
#couldn't find solution
q = np.random.randint(1,9,size=(5,3))
r = np.where(q>4)
print(q)
print(r)
np.put(q,r,(q**2))

[[8 7 7]
 [7 3 8]
 [5 6 8]
 [2 4 3]
 [1 5 4]]
(array([0, 0, 0, 1, 1, 2, 2, 2, 4], dtype=int64), array([0, 1, 2, 0, 2, 0, 1, 2, 1], dtype=int64))
